./systemSetupAndSimulationSaveErrorsBothArmsLabel.sh
./systemSetupAndSimulationSaveErrorsLeftArmLabel.sh
./systemSetupAndSimulationSaveErrorsRightArmLabel.sh
./systemSetupAndSimulationSaveErrorsLocomotion.sh